[package]
name = "CustomUi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = "*"
figment = { version = "*", features = ["json", "env"] }
serde = { version = "*", features = ["derive"] }